// Generated by: main.exe
// TypeWriter: stringer
// Directive: +gen on ExpressionType

package internals

import (
	"fmt"
)

const _ExpressionType_name = "ExpressionTypeIntervalValueExpressionTypeSecondsExpressionTypeMinutesExpressionTypeHoursExpressionTypeDaysOfWeekExpressionTypeDaysOfMonthExpressionTypeDates"

var _ExpressionType_index = [...]uint8{0, 27, 48, 69, 88, 112, 137, 156}

func (i ExpressionType) String() string {
	i -= 1
	if i < 0 || i+1 >= ExpressionType(len(_ExpressionType_index)) {
		return fmt.Sprintf("ExpressionType(%d)", i+1)
	}
	return _ExpressionType_name[_ExpressionType_index[i]:_ExpressionType_index[i+1]]
}
